//! Central dispatch for external (non-special-builtin) commands.
//!
//! Used by the execution engine after [`crate::interpreter::builtin_dispatch::dispatch_builtin`]
//! returns `Ok(None)`.

use crate::commands::{
    alias_cmd::AliasCommand,
    awk::AwkCommand,
    base64_cmd::Base64Command,
    basename::BasenameCommand,
    bash_cmd::{BashCommand, ShCommand},
    cat::CatCommand,
    chmod::ChmodCommand,
    clear_cmd::ClearCommand,
    column_cmd::ColumnCommand,
    comm_cmd::CommCommand,
    cp::CpCommand,
    curl::CurlCommand,
    cut::CutCommand,
    date::DateCommand,
    diff_cmd::DiffCommand,
    dirname::DirnameCommand,
    du_cmd::DuCommand,
    echo::EchoCommand,
    env::{EnvCommand, PrintenvCommand},
    expand_cmd::ExpandCommand,
    expr_cmd::ExprCommand,
    file_cmd::FileCommand,
    find::FindCommand,
    fold_cmd::FoldCommand,
    grep::GrepCommand,
    gzip::{GunzipCommand, GzipCommand, ZcatCommand},
    head::HeadCommand,
    help_cmd::HelpCommand,
    history_cmd::HistoryCommand,
    hostname_cmd::HostnameCommand,
    html_to_markdown_cmd::HtmlToMarkdownCommand,
    join::JoinCommand,
    jq::JqCommand,
    ln::LnCommand,
    ls::LsCommand,
    md5sum::{Md5sumCommand, Sha1sumCommand, Sha256sumCommand},
    mkdir::MkdirCommand,
    mv::MvCommand,
    nl::NlCommand,
    od_cmd::OdCommand,
    paste::PasteCommand,
    printf::PrintfCommand,
    pwd::PwdCommand,
    readlink_cmd::ReadlinkCommand,
    rev_cmd::RevCommand,
    rg_cmd::RgCommand,
    rm::RmCommand,
    rmdir_cmd::RmdirCommand,
    sed::SedCommand,
    seq::SeqCommand,
    sleep_cmd::SleepCommand,
    sort::SortCommand,
    split_cmd::SplitCommand,
    stat_cmd::StatCommand,
    strings_cmd::StringsCommand,
    tac_cmd::TacCommand,
    tail::TailCommand,
    tar::TarCommand,
    tee::TeeCommand,
    test_cmd::{BracketCommand, TestCommand},
    time_cmd::TimeCommand,
    timeout_cmd::TimeoutCommand,
    touch::TouchCommand,
    tr::TrCommand,
    tree_cmd::TreeCommand,
    true_cmd::FalseCommand,
    true_cmd::TrueCommand,
    unalias_cmd::UnaliasCommand,
    uniq::UniqCommand,
    wc::WcCommand,
    which_cmd::WhichCommand,
    whoami_cmd::WhoamiCommand,
    xan_cmd::XanCommand,
    xargs::XargsCommand,
    yq::YqCommand,
};
use crate::commands::{Command, CommandContext, CommandResult};

macro_rules! dispatch_external {
    ($name:expr, $ctx:expr, { $( $pat:pat => $cmd:ident ),* $(,)? }) => {
        match $name {
            $( $pat => <$cmd as Command>::execute(&$cmd, $ctx).await , )*
            _ => CommandResult::with_exit_code(
                String::new(),
                format!("bash: {}: command not found\n", $name),
                127,
            ),
        }
    };
}

/// Run an external command by simple name with the given context.
pub async fn dispatch_external_command(name: &str, ctx: CommandContext) -> CommandResult {
    dispatch_external!(name, ctx, {
        "alias" => AliasCommand,
        "awk" | "gawk" | "mawk" => AwkCommand,
        "base64" => Base64Command,
        "basename" => BasenameCommand,
        "bash" => BashCommand,
        "sh" => ShCommand,
        "cat" => CatCommand,
        "chmod" => ChmodCommand,
        "clear" => ClearCommand,
        "column" => ColumnCommand,
        "comm" => CommCommand,
        "cp" => CpCommand,
        "curl" => CurlCommand,
        "cut" => CutCommand,
        "date" => DateCommand,
        "diff" => DiffCommand,
        "dirname" => DirnameCommand,
        "du" => DuCommand,
        "echo" => EchoCommand,
        "env" => EnvCommand,
        "expand" => ExpandCommand,
        "expr" => ExprCommand,
        "file" => FileCommand,
        "find" => FindCommand,
        "fold" => FoldCommand,
        "grep" => GrepCommand,
        "gzip" => GzipCommand,
        "gunzip" => GunzipCommand,
        "zcat" => ZcatCommand,
        "head" => HeadCommand,
        "help" => HelpCommand,
        "history" => HistoryCommand,
        "html-to-markdown" => HtmlToMarkdownCommand,
        "hostname" => HostnameCommand,
        "join" => JoinCommand,
        "jq" => JqCommand,
        "ln" => LnCommand,
        "ls" => LsCommand,
        "md5sum" => Md5sumCommand,
        "sha1sum" => Sha1sumCommand,
        "sha256sum" => Sha256sumCommand,
        "mkdir" => MkdirCommand,
        "mv" => MvCommand,
        "nl" => NlCommand,
        "od" => OdCommand,
        "paste" => PasteCommand,
        "printf" => PrintfCommand,
        "printenv" => PrintenvCommand,
        "pwd" => PwdCommand,
        "readlink" => ReadlinkCommand,
        "rev" => RevCommand,
        "rg" => RgCommand,
        "rm" => RmCommand,
        "rmdir" => RmdirCommand,
        "sed" => SedCommand,
        "seq" => SeqCommand,
        "sleep" => SleepCommand,
        "sort" => SortCommand,
        "split" => SplitCommand,
        "stat" => StatCommand,
        "strings" => StringsCommand,
        "tac" => TacCommand,
        "tail" => TailCommand,
        "tar" => TarCommand,
        "tee" => TeeCommand,
        "test" => TestCommand,
        "[" => BracketCommand,
        "time" => TimeCommand,
        "timeout" => TimeoutCommand,
        "touch" => TouchCommand,
        "tr" => TrCommand,
        "tree" => TreeCommand,
        "true" => TrueCommand,
        "false" => FalseCommand,
        "uniq" => UniqCommand,
        "unalias" => UnaliasCommand,
        "wc" => WcCommand,
        "which" => WhichCommand,
        "whoami" => WhoamiCommand,
        "xan" => XanCommand,
        "xargs" => XargsCommand,
        "yq" => YqCommand,
    })
}
